language: php
dist: trusty
group: edge

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer dump-autoload -o
  - if [[ $TRAVIS_PHP_VERSION = 'nightly' ]]; then git clone git://github.com/xdebug/xdebug.git && cd xdebug && phpize && ./configure --enable-xdebug  && make && make install && echo "zend_extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && cd ..; fi

script:
  - bin/kahlan --coverage=4 --reporter=verbose --clover=build/logs/clover.xml
  - bin/php-coveralls -v --exclude-no-stmt

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly